eureka:
client:
  register-with-eureka: false

server:
  port: ${GATEWAY_SERVICE_PORT:8080}

security:
  jwt:
    access:
      token:
        secret: levc/guxCQY5xgOePnfbG52ZjB4Jn+PvZMK+DBxwBKHG3ODmlQQ8FBWO4juJkTJd1htUl82Io+LAz54kKbKmQw==

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: account
          uri: lb://ACCOUNT
          predicates:
            - Path=/api/auth/**, /api/account/**, /api/admin/**
        - id: flow
          uri: lb://FLOW
          predicates:
              - Path=/flow/**
        - id: manager
          uri: lb://MANAGER
          predicates:
              - Path=/manager/**